document.writeln("<html>");
document.writeln("");
document.writeln("");
document.writeln("<head>");
document.writeln("    <script src=\'http://www.vxia.net/source/other/static/jquery.min.js\'></script>");
document.writeln("    <style>");
document.writeln("        html, body {");
document.writeln("            background: #000;");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("        }");
document.writeln("");
document.writeln("        canvas {");
document.writeln("            width: 100%;");
document.writeln("            height: 100%;");
document.writeln("            position: absolute;");
document.writeln("        }");
document.writeln("");
document.writeln("        /* Demo Buttons Style */");
document.writeln("        .codrops-demos {");
document.writeln("            font-size: 0.8em;");
document.writeln("            text-align: center;");
document.writeln("            position: absolute;");
document.writeln("            z-index: 99;");
document.writeln("            width: 96%;");
document.writeln("        }");
document.writeln("");
document.writeln("            .codrops-demos a {");
document.writeln("                display: inline-block;");
document.writeln("                margin: 0.35em 0.1em;");
document.writeln("                padding: 0.5em 1.2em;");
document.writeln("                outline: none;");
document.writeln("                text-decoration: none;");
document.writeln("                text-transform: uppercase;");
document.writeln("                letter-spacing: 1px;");
document.writeln("                font-weight: 700;");
document.writeln("                border-radius: 2px;");
document.writeln("                font-size: 110%;");
document.writeln("                border: 2px solid transparent;");
document.writeln("                color: #fff;");
document.writeln("            }");
document.writeln("");
document.writeln("                .codrops-demos a:hover,");
document.writeln("                .codrops-demos a.current-demo {");
document.writeln("                    border-color: #0080ff;");
document.writeln("                }");
document.writeln("    </style>");
document.writeln("    <style type=\'text/css\'>");
document.writeln("        .tb960x90 {");
document.writeln("            display: none !important;");
document.writeln("            display: none");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("    <canvas width=\'1366\' height=\'634\'></canvas>");
document.writeln("    <script>");
document.writeln("        $(function () {");
document.writeln("            var canvas = document.querySelector(\'canvas\'),");
document.writeln("                ctx = canvas.getContext(\'2d\')");
document.writeln("");
document.writeln("            canvas.width = window.innerWidth;");
document.writeln("            canvas.height = window.innerHeight;");
document.writeln("            ctx.lineWidth = .3;");
document.writeln("            ctx.strokeStyle = (new Color(150)).style;");
document.writeln("");
document.writeln("            var mousePosition = {");
document.writeln("                x: 30 * canvas.width / 100,");
document.writeln("                y: 30 * canvas.height / 100");
document.writeln("            };");
document.writeln("");
document.writeln("            var dots = {");
document.writeln("                nb: 750,");
document.writeln("                distance: 50,");
document.writeln("                d_radius: 100,");
document.writeln("                array: []");
document.writeln("            };");
document.writeln("");
document.writeln("            function colorValue(min) {");
document.writeln("                return Math.floor(Math.random() * 255 + min);");
document.writeln("            }");
document.writeln("");
document.writeln("            function createColorStyle(r, g, b) {");
document.writeln("                return \'rgba(\' + r + \',\' + g + \',\' + b + \', 0.8)\';");
document.writeln("            }");
document.writeln("");
document.writeln("            function mixComponents(comp1, weight1, comp2, weight2) {");
document.writeln("                return (comp1 * weight1 + comp2 * weight2) / (weight1 + weight2);");
document.writeln("            }");
document.writeln("");
document.writeln("            function averageColorStyles(dot1, dot2) {");
document.writeln("                var color1 = dot1.color,");
document.writeln("                    color2 = dot2.color;");
document.writeln("");
document.writeln("                var r = mixComponents(color1.r, dot1.radius, color2.r, dot2.radius),");
document.writeln("                    g = mixComponents(color1.g, dot1.radius, color2.g, dot2.radius),");
document.writeln("                    b = mixComponents(color1.b, dot1.radius, color2.b, dot2.radius);");
document.writeln("                return createColorStyle(Math.floor(r), Math.floor(g), Math.floor(b));");
document.writeln("            }");
document.writeln("");
document.writeln("            function Color(min) {");
document.writeln("                min = min || 0;");
document.writeln("                this.r = colorValue(min);");
document.writeln("                this.g = colorValue(min);");
document.writeln("                this.b = colorValue(min);");
document.writeln("                this.style = createColorStyle(this.r, this.g, this.b);");
document.writeln("            }");
document.writeln("");
document.writeln("            function Dot() {");
document.writeln("                this.x = Math.random() * canvas.width;");
document.writeln("                this.y = Math.random() * canvas.height;");
document.writeln("");
document.writeln("                this.vx = -.5 + Math.random();");
document.writeln("                this.vy = -.5 + Math.random();");
document.writeln("");
document.writeln("                this.radius = Math.random() * 2;");
document.writeln("");
document.writeln("                this.color = new Color();");
document.writeln("                console.log(this);");
document.writeln("            }");
document.writeln("");
document.writeln("            Dot.prototype = {");
document.writeln("                draw: function () {");
document.writeln("                    ctx.beginPath();");
document.writeln("                    ctx.fillStyle = this.color.style;");
document.writeln("                    ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2, false);");
document.writeln("                    ctx.fill();");
document.writeln("                }");
document.writeln("            };");
document.writeln("");
document.writeln("            function createDots() {");
document.writeln("                for (i = 0; i < dots.nb; i++) {");
document.writeln("                    dots.array.push(new Dot());");
document.writeln("                }");
document.writeln("            }");
document.writeln("");
document.writeln("            function moveDots() {");
document.writeln("                for (i = 0; i < dots.nb; i++) {");
document.writeln("");
document.writeln("                    var dot = dots.array[i];");
document.writeln("");
document.writeln("                    if (dot.y < 0 || dot.y > canvas.height) {");
document.writeln("                        dot.vx = dot.vx;");
document.writeln("                        dot.vy = - dot.vy;");
document.writeln("                    }");
document.writeln("                    else if (dot.x < 0 || dot.x > canvas.width) {");
document.writeln("                        dot.vx = - dot.vx;");
document.writeln("                        dot.vy = dot.vy;");
document.writeln("                    }");
document.writeln("                    dot.x += dot.vx;");
document.writeln("                    dot.y += dot.vy;");
document.writeln("                }");
document.writeln("            }");
document.writeln("");
document.writeln("            function connectDots() {");
document.writeln("                for (i = 0; i < dots.nb; i++) {");
document.writeln("                    for (j = 0; j < dots.nb; j++) {");
document.writeln("                        i_dot = dots.array[i];");
document.writeln("                        j_dot = dots.array[j];");
document.writeln("");
document.writeln("                        if ((i_dot.x - j_dot.x) < dots.distance && (i_dot.y - j_dot.y) < dots.distance && (i_dot.x - j_dot.x) > - dots.distance && (i_dot.y - j_dot.y) > - dots.distance) {");
document.writeln("                            if ((i_dot.x - mousePosition.x) < dots.d_radius && (i_dot.y - mousePosition.y) < dots.d_radius && (i_dot.x - mousePosition.x) > - dots.d_radius && (i_dot.y - mousePosition.y) > - dots.d_radius) {");
document.writeln("                                ctx.beginPath();");
document.writeln("                                ctx.strokeStyle = averageColorStyles(i_dot, j_dot);");
document.writeln("                                ctx.moveTo(i_dot.x, i_dot.y);");
document.writeln("                                ctx.lineTo(j_dot.x, j_dot.y);");
document.writeln("                                ctx.stroke();");
document.writeln("                                ctx.closePath();");
document.writeln("                            }");
document.writeln("                        }");
document.writeln("                    }");
document.writeln("                }");
document.writeln("            }");
document.writeln("");
document.writeln("            function drawDots() {");
document.writeln("                for (i = 0; i < dots.nb; i++) {");
document.writeln("                    var dot = dots.array[i];");
document.writeln("                    dot.draw();");
document.writeln("                }");
document.writeln("            }");
document.writeln("");
document.writeln("            function animateDots() {");
document.writeln("                ctx.clearRect(0, 0, canvas.width, canvas.height);");
document.writeln("                moveDots();");
document.writeln("                connectDots();");
document.writeln("                drawDots();");
document.writeln("");
document.writeln("                requestAnimationFrame(animateDots);");
document.writeln("            }");
document.writeln("");
document.writeln("            $(\'canvas\').on(\'mousemove\', function (e) {");
document.writeln("                mousePosition.x = e.pageX;");
document.writeln("                mousePosition.y = e.pageY;");
document.writeln("            });");
document.writeln("");
document.writeln("            $(\'canvas\').on(\'mouseleave\', function (e) {");
document.writeln("                mousePosition.x = canvas.width / 2;");
document.writeln("                mousePosition.y = canvas.height / 2;");
document.writeln("            });");
document.writeln("");
document.writeln("            createDots();");
document.writeln("            requestAnimationFrame(animateDots);");
document.writeln("        });");
document.writeln("    </script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");